apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-test
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  source:
    chart: webapp1
    repoURL: https://raw.githubusercontent.com/alexandrov-ua/helm-repo/main
    targetRevision: 1.16.1
    helm:
      releaseName: my-web-app
      valuesObject:
        name: my-web-app
